.catalog:
    name: "Rancher Rebalancer"
    version: "v0.1.0"
    description: "Rancher Rebalancer"
    minimum_rancher_version: v1.5.5

rancher-rebalancer:
    health_check:
        port: 9777
        interval: 2000
        unhealthy_threshold: 3
        strategy: recreate
        response_timeout: 2000
        request_line: GET /ping HTTP/1.0
        healthy_threshold: 2