.catalog:
    name: "AWS Host Cleanup"
    version: "v0.1.0"
    description: "AWS Host Cleanup"
    questions:
     - variable: "AWS_ACCESS_KEY_ID"
       description: "AWS Access Key"
       label: "AWS Access Key"
       required: true
       type: "string"
     - variable: "AWS_SECRET_ACCESS_KEY"
       description: "AWS Secret Key"
       label: "Access Secret"
       required: true
       type: "string" 