ds-remove:
  image: chrisurwin/ds-remove:v0.1.0
  tty: true
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    ARN: "${ARN}"
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
    io.rancher.scheduler.global: 'true'