aws-spot-instance-helper:
  image: chrisurwin/autospotting:v0.1.0
  tty: true
  labels:
    io.rancher.container.pull_image: always
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"